version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - if [ "$RUN_BUILD_TO_EC2" == "true" ]; then
          echo "Running Build-to-EC2 stage";
          # Add your deployment commands here (e.g., deploy to EC2)
        else
          echo "Skipping Build-to-EC2 stage";
        fi
