version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - if [ "$SKIP_BUILD" == "true" ]; then exit 0; fi
  build:
    commands:
      - echo "Running build"
  post_build:
    commands:
      - echo "Post-build phase"
